### ISSUE TITLE
#Compiled Version

### ISSUE THREAD

**Issue by HaiAnhh** [unixpickle/JamWiFi#13]
Hello, 
Thanks for the amazing application
But can you as well upload an complied version?
My Mac doesn't have yet downloaded XCode (too heavy to my mac's network :( ) and can not yet use the app to clear the net.

Thanks.

**Comment by unixpickle** [comment]
There are some forks which include packaged binaries. I will not endorse these since I did not do the build myself, but you might want to check them out.
