### ISSUE TITLE
Only work for Channel 1. (2.4GHz)

### ISSUE THREAD

**Issue by xuwenge** [unixpickle/JamWiFi#17]
I tested it, and it only works for Channel 1. But it;s a nice job you have done!

**Comment by unixpickle** [comment]
It should work for all 2.4GHz channels--I've used it on channels other than 1. However, it may not work against all devices/routers depending on how fast they can reconnect.

I doubt this works properly for 5GHz channels. I have never tested that.

**Comment by xuwenge** [comment]
Now it works, thx.
