### ISSUE TITLE
How does JamWiFi finds the mac address of the devices associated with a network?

### ISSUE THREAD

**Issue by huangzonghao** [unixpickle/JamWiFi#23]
This tool is awesome! Thanks for building it!

I am just wondering which tool you are using to get the mac address of the devices which are exchanging packets with the AP? Are there any neat tool that I can use in command line? Thanks!

**Comment by unixpickle** [comment]
Currently, I put the WiFi card into promiscuous mode and then use libpcap to capture all the packets being received by the card. This includes packets from other hosts, and the MACs of these hosts are stored in an unencrypted fashion.
