### ISSUE TITLE
channel hopping error

### ISSUE THREAD

**Issue by JiantaoFu** [unixpickle/JamWiFi#8]
if (hopChannel) {
                    NSError *err = nil;
                    [[interface interface] setWLANChannel:hopChannel error:&err];
                    hopChannel = nil;
                }

(NSError *) $0 = 0x0000600000051c40 domain: @"com.apple.wifi.apple80211API.error" - code: 18446744073709547713

**Comment by JiantaoFu** [comment]
Moving disassociate into initWithInterface and use - (BOOL)setChannel:(NSInteger)channel fix this problem

- (id)initWithInterface:(NSString *)name {
    if ((self = [super init])) {
        interface = [[CWInterface alloc] initWithInterfaceName:name];
        [interface disassociate];

**Comment by unixpickle** [comment]
It would be awesome if you could submit a pull request.
